name: C++ Build

on:
  pull_request:
    branches:
      - assignment3
      - assignment4
      - main
  push:
    branches:
      - main
      - assignment3
      - assignment4

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install C++ compiler, build tools, Doxygen, and Xerces
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
        sudo apt-get install -y cmake
        sudo apt-get install -y doxygen
        sudo apt-get install -y libxerces-c-dev
        sudo apt-get install -y xsdcxx
        
    - name: Build C++ code
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Run unit tests
      run: |
        cd build
        ctest --output-on-failure
