name: C++ Build

on:
  push:
    branches:
      - assignment2

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up C++ compiler
      uses: actions/setup-cpp@v2
      with:
        compiler: 'gcc'
        
    - name: Build C++ code
      run: |
        mkdir build
        cd build
        cmake ..
        make
